### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by SimonMellerin** [YunoHost-Apps/phpinfo_ynh#1]
Hi,

I was trying to use ynh_install_php experimental helpers for Pilea, I based my work in this app.
My script failed so I tried to install this app and I failed too :/

I use a freshly installed ynh server in VirtualBox, here is the log : https://paste.yunohost.org/raw/iburexupoj

**Comment by SimonMellerin** [comment]
I had the same error while using this helper with Pilea so maybe the right place to open this issue is in https://github.com/YunoHost-Apps/Experimental_helpers

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost/yunohost/blob/stretch-unstable/debian/changelog#L28
My bad, this dependence is still in testing.

You can add it as a dependence of your app meanwhile.
